-- Migration 061: Cleanup duplicate smart/smart_per_child accruals generated by superseded or future rates

UPDATE salary_transactions st
SET is_deleted = true,
    deleted_at = NOW()
FROM staff_rates sr
WHERE st.rate_id = sr.id
  AND st.type = 'ACCRUAL'
  AND st.is_deleted = false
  AND sr.rate_type IN ('smart', 'smart_per_child')
  AND (
    (sr.valid_from IS NOT NULL AND st.billing_month < DATE_TRUNC('month', sr.valid_from::timestamp + INTERVAL '1 day'))
    OR
    (sr.valid_to IS NOT NULL AND st.billing_month >= DATE_TRUNC('month', sr.valid_to::timestamp + INTERVAL '1 day'))
  );
